name: Build & release geosite.dat

on:
  # دستی از تب Actions اجرا می‌کنی
  workflow_dispatch:

jobs:
  build:
    name: Build geosite.dat and create release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
        shell: bash

      - name: Build geosite.dat file
        run: |
          # همین ریشه‌ی ریپو هستیم، اینجا .git هم وجود داره
          mkdir -p build
          go run ./ --outputdir=./build
          mv build/dlc.dat build/geosite.dat

      - name: Generate geosite.dat sha256 hash
        run: |
          sha256sum build/geosite.dat > build/geosite.dat.sha256sum

      - name: Create GitHub Release and upload assets
        run: |
          gh release create "${{ env.TAG_NAME }}" \
            --generate-notes \
            --latest \
            --title "${{ env.RELEASE_NAME }}" \
            build/geosite.dat build/geosite.dat.sha256sum
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
